name: Whyth Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install dependencies
        run: go mod download

      - name: Build the Go binary
        run: go build -o backend .

      - name: Upload the built binary
        uses: actions/upload-artifact@v2
        with:
          name: backend-binary
          path: ./backend

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace environment variables in env_file
        run: |
          envsubst < .env.example > env
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SERVER_PORT: ${{ vars.SERVER_PORT }}

      - name: Copy the presets.json to the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.BACKEND_DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: presets.json
          target: /root/backend
      
      - name: Copy env_file to the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.BACKEND_DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: env
          target: /root/env

      - name: Download the built binary
        uses: actions/download-artifact@v2
        with:
          name: backend-binary

      - name: Copy the binary to the backend droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.BACKEND_DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./backend
          target: /root/backend

      - name: SSH into the backend droplet and restart the backend service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BACKEND_DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            chmod +x /root/backend/backend
            systemctl restart curly-meme.service